spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:7080/realms/master/protocol/openid-connect/certs
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
        enabled: true
    discovery:
      client:
        health-indicator:
          enabled: false
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      httpclient:
        connect-timeout: 2000
        response-timeout: 10s
  application:
    name: gatewayserver
  profiles:
    active: local
  config:
    import: optional:configserver:http://${CONFIG_SERVER_HOST:localhost}:8071/
